trigger:
- azure-pipelines-docker

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:    
    - task: Docker@2
      displayName: Build WebApi
      inputs:
        containerRegistry: 'GKE registry'
        repository: 'identifier-generator/webapi'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/IdentifierGenerator.WebApi/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: '$(tag)'
    - task: Docker@2
      enabled: false
      displayName: Build Web.Angular
      inputs:
        containerRegistry: 'GKE registry'
        repository: 'identifier-generator/nginx-ng'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/IdentifierGenerator.Web.Angular/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: '$(tag)'