version: '3.8'

services:
  webapi:
    image: identifier-generator/webapi
    depends_on:
      - sqldb
    build:
      context: ../..
      dockerfile: src/IdentifierGenerator.WebApi/Dockerfile
    ports:
      - 8180:80

  nginx-ng:
    image: identifier-generator/nginx-ng
    depends_on:
      - webapi
    build:
      context: ../..
      dockerfile: src/IdentifierGenerator.Web.Angular/Dockerfile
    ports:
      - 8080:80

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "kask7HsAzaXzG"
        MSSQL_PID: "Express"
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - 1433:1433

volumes:
  sqlvolume: