version: '3.8'

services:
  webapi:
    image: identifier-generator/webapi
    depends_on:
      - sqldb
    build:
      context: ../..
      dockerfile: src/IdentifierGenerator.WebApi/Dockerfile
    ports:
      - 8180:80

  nginx-ng:
    image: identifier-generator/nginx-ng
    depends_on:
      - webapi
    build:
      context: ../..
      dockerfile: src/IdentifierGenerator.Web.Angular/Dockerfile
    ports:
      - 8080:80

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "kask7HsAzaXzG"
        MSSQL_PID: "Express"
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - 1433:1433
      
  tools-health-check-watchdog:
    image: identifier-generator/tools-health-check-watchdog
    build:
      context: ../..
      dockerfile: src/Tools.HealthCheckWatchdog/Dockerfile
    environment:
      HealthChecks-UI__HealthChecks__0__Name: Identifier Generator
      HealthChecks-UI__HealthChecks__0__Uri: http://webapi/health/ready
    ports:
      - 8280:80

volumes:
  sqlvolume: