// <auto-generated />
using System;
using IdentifierGenerator.Infrastructure.DbContextConfiguration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentifierGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(IdentifierGeneratorDbContext))]
    [Migration("20190505180139_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentifierGenerator.Model.Domain.Identifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(30);

                    b.Property<string>("FactoryCode")
                        .HasMaxLength(30);

                    b.Property<Guid>("GlobalId");

                    b.Property<int>("Value")
                        .IsConcurrencyToken();

                    b.HasKey("Id");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("FactoryCode", "CategoryCode");

                    b.ToTable("Identifier");
                });

            modelBuilder.Entity("IdentifierGenerator.Model.Domain.IdentifierGenerated", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<DateTime>("GeneratedOn");

                    b.Property<Guid>("IdentifierGlobalId");

                    b.HasKey("Id");

                    b.HasIndex("IdentifierGlobalId");

                    b.ToTable("IdentifierGenerated");
                });
#pragma warning restore 612, 618
        }
    }
}
