# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '793fb093-17e0-4924-82e3-21ba48b0fbd8'
    pipeline: '3'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: Bash@3
  displayName: 'List artifacts'
  inputs:
    targetType: 'inline'
    script: |
      ls $(System.ArtifactsDirectory)
  
- task: Bash@3
  displayName: Install terraform'
  inputs:
    targetType: 'inline'
    script: |
      wget https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip -O terraform.zip
      unzip terraform.zip
      install terraform $(Agent.ToolsDirectory)
      rm terraform.zip

- task: Bash@3
  displayName: 'Get terraform version'
  inputs:
    targetType: 'inline'
    script: |
      terraform --version