apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ng-configmap
  namespace: {{ .Values.namespace }}
data:
  configuration: |-
    {
      "apiUrl": {{ printf "%s%s" .Values.webapiUrlScheme .Values.webapiHost | quote }}
    }