IF DB_ID(N'$(DATABASENAME)') IS NOT NULL
BEGIN;
	PRINT 'Database $(DATABASENAME) already exists. Exiting...'
    SET NOEXEC ON
END

PRINT 'Database $(DATABASENAME) does not exist.';
PRINT 'Creating $(DATABASENAME)...';

USE [master]
CREATE DATABASE [$(DATABASENAME)]
GO

CREATE LOGIN [$(USERNAME)] WITH PASSWORD=N'$(USERPASSWORD)', DEFAULT_DATABASE=[$(DATABASENAME)], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [$(DATABASENAME)];
GO
CREATE USER [$(USERNAME)] FOR LOGIN [$(USERNAME)]
GO
ALTER ROLE [db_owner] ADD MEMBER [$(USERNAME)]
GO


SET NOEXEC OFF 