apiVersion: v1
kind: Secret
metadata:
  name: sqldb-secret-webapi-connection
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  databasename: {{ .Values.sql.databaseName | quote }}
  username: {{ .Values.sql.webApiUserName | quote }}
  password: {{ .Values.sql.webApiUserPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sqldb-secret-sa
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.sql.saPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webapi-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  webapi: |-
    {
      "ConnectionStrings": {
        "IdentifierGeneratorContext": "Server=sqldb;Database={{.Values.sql.databaseName}};User Id={{.Values.sql.webApiUserName}};Password={{.Values.sql.webApiUserPassword}}"
      }
    }